In [ ]:
#Importing all libraries

In [21]:
import numpy as np
import pandas as pd
from sklearn import preprocessing,neighbors

from sklearn import metrics
from sklearn.model_selection import train_test_split
#import matplotlib.pyplot as plt
#from sklearn.cluster import KMeans

In [ ]:
mango2.csv

In [ ]:
#Open the dataset

In [94]:
df = pd.read_csv('data set/vehicle dataset KNN.txt')

In [95]:
df.head()

id  heigt  wt  lenght  passenger  color tire  fule  year  made  class
0  1000025      5   1       1          1      2    1     3     1     1      2
1  1002945      5   4       4          5      7   10     3     2     1      2
2  1015425      3   1       1          1      2    2     3     1     1      2
3  1016277      6   8       8          1      3    4     3     7     1      2
4  1017023      4   1       1          3      2    1     3     1     1      2

In [ ]:
#df.info()

In [96]:
df.dtypes

id            int64
heigt         int64
wt            int64
lenght        int64
passenger     int64
color         int64
tire         object
fule          int64
year          int64
made          int64
class         int64
dtype: object

In [ ]:
#display(df)

In [ ]:
#df.isnull().any()

In [ ]:
#df['tire'].replace('?', 0, inplace=True)

In [ ]:
#df.dtypes

In [98]:
df.replace('?', 1, inplace=True)

In [99]:
df['tire'] = df['tire'].astype(int)

In [ ]:
# We drop 1 st colomun

In [66]:
df.drop(['id','tire'], axis=1, inplace=True)

In [93]:
df.drop(['id'], axis=1, inplace=True)

KeyError: "['id'] not found in axis"

In [67]:
df.head(20)

heigt  wt  lenght  passenger  color  fule  year  made  class
0       5   1       1          1      2     3     1     1      2
1       5   4       4          5      7     3     2     1      2
2       3   1       1          1      2     3     1     1      2
3       6   8       8          1      3     3     7     1      2
4       4   1       1          3      2     3     1     1      2
5       8  10      10          8      7     9     7     1      4
6       1   1       1          1      2     3     1     1      2
7       2   1       2          1      2     3     1     1      2
8       2   1       1          1      2     1     1     5      2
9       4   2       1          1      2     2     1     1      2
10      1   1       1          1      1     3     1     1      2
11      2   1       1          1      2     2     1     1      2
12      5   3       3          3      2     4     4     1      4
13      1   1       1          1      2     3     1     1      2
14      8   7       5         10      7     5     5     4      4
15      7   4       6          4      6     4     3     1      4
16      4   1       1          1      2     2     1     1      2
17      4   1       1          1      2     3     1     1      2
18     10   7       7          6      4     4     1     2      4
19      6   1       1          1      2     3     1     1      2

In [ ]:
df['tire'].isnull().any()

In [ ]:
#Define x values
#defining the features(x) and laberls(y)

In [82]:
x = np.array(df.drop(['class'], 1))
y = np.array(df['class'])

In [83]:
print(x)

[[5 1 1 ... 3 1 1]
 [5 4 4 ... 3 2 1]
 [3 1 1 ... 3 1 1]
 ...
 [5 10 10 ... 8 10 2]
 [4 8 6 ... 10 6 1]
 [4 8 8 ... 10 4 1]]


In [84]:
x

array([[5, 1, 1, ..., 3, 1, 1],
       [5, 4, 4, ..., 3, 2, 1],
       [3, 1, 1, ..., 3, 1, 1],
       ...,
       [5, 10, 10, ..., 8, 10, 2],
       [4, 8, 6, ..., 10, 6, 1],
       [4, 8, 8, ..., 10, 4, 1]], dtype=object)

In [85]:
print(y)

[2 2 2 2 2 4 2 2 2 2 2 2 4 2 4 4 2 2 4 2 4 4 2 4 2 4 2 2 2 2 2 2 4 2 2 2 4
 2 4 4 2 4 4 4 4 2 4 2 2 4 4 4 4 4 4 4 4 4 4 4 4 2 4 4 2 4 2 4 4 2 2 4 2 4
 4 2 2 2 2 2 2 2 2 2 4 4 4 4 2 2 2 2 2 2 2 2 2 2 4 4 4 4 2 4 4 4 4 4 2 4 2
 4 4 4 2 2 2 4 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 2 2 2 2 2 2 2 2 2 4 2 2 2 4 2
 2 4 2 4 4 2 2 4 2 2 2 4 4 2 2 2 2 2 4 4 2 2 2 2 2 4 4 4 2 4 2 4 2 2 2 4 4
 2 4 4 4 2 4 4 2 2 2 2 2 2 2 2 4 4 2 2 2 4 4 2 2 2 4 4 2 4 4 4 2 2 4 2 2 4
 4 4 4 2 4 4 2 4 4 4 2 4 2 2 4 4 4 4 2 2 2 2 2 2 4 4 2 2 2 4 2 4 4 4 2 2 2
 2 4 4 4 4 4 2 4 4 4 2 4 2 4 4 2 2 2 2 2 4 2 2 4 4 4 4 4 2 4 4 2 2 4 4 2 4
 2 2 2 4 4 2 4 2 4 4 2 2 4 2 2 2 4 2 2 2 4 4 2 2 4 2 2 4 2 2 4 2 4 4 4 2 2
 4 4 2 4 2 2 4 4 2 2 2 4 2 2 2 4 4 2 2 2 4 2 2 4 4 4 4 4 4 2 2 2 2 4 4 2 2
 2 2 2 2 2 2 2 2 2 2 2 4 2 2 2 2 4 2 2 2 2 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 2
 2 2 2 2 2 4 2 4 2 4 2 2 2 2 4 2 2 2 4 2 4 2 2 2 2 2 2 2 4 4 2 2 2 4 2 2 2
 2 2 2 2 2 4 2 2 2 4 2 4 4 4 2 2 2 2 2 2 2 4 4 4 2 2 2 2 2 2 2 2 2 2 2 4 2
 2 4 4 2 2 2 4 4 4 2 4 2 

In [86]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [87]:
#We are defining classifier and then trainin it usin:
clf = neighbors.KNeighborsClassifier()
clf.fit(x_train, y_train)
accuracy = clf.score(x_train, y_train)
print(accuracy)

0.9785330948121646


In [ ]:
X = df.iloc[:, [0,1,2,3]].values

In [ ]:
# Lets find out optimum values of the clusters using elobow method

In [ ]:
kmeans = KMeans(n_clusters=3, init = 'k-means++', max_iter=300, n_init=10, random_state=0)
y_kmeans = kmeans.fit_predict(X)


In [ ]:
plt.scatter(X[y_kmeans==0, 0], X[y_kmeans==0,1], s=100, c='red', label ='Cluster 0')
plt.scatter(X[y_kmeans==1, 0], X[y_kmeans==1,1], s=100, c='blue', label ='Cluster 1')
plt.scatter(X[y_kmeans==2, 0], X[y_kmeans==2,1], s=100, c='Green', label ='Cluster 2')


In [ ]:
#Import Libaries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
#Import the data with pandas

df = pd.read_csv('mango2.csv')
#print(df.head(3))
#Define x values
X = df.iloc[:, [0,1,2,3]].values

# Lets find out optimum values of the clusters using elobow method

#sq = []
#for i in range(1, 11):
#    kmeans = KMeans(n_clusters = i, init = 'k-means++', max_iter =300,
#                    n_init =10, random_state =0)
#   kmeans.fit(X)
#    sq.append(kmeans.inertia_)
#plot the elbow graph
#plt.plot(range(1,11), sq)
#plt.show()

kmeans = KMeans(n_clusters=3, init = 'k-means++', max_iter=300, n_init=10, random_state=0)
y_kmeans = kmeans.fit_predict(X)

plt.scatter(X[y_kmeans==0, 0], X[y_kmeans==0,1], s=100, c='red', label ='Cluster 0')
plt.scatter(X[y_kmeans==1, 0], X[y_kmeans==1,1], s=100, c='blue', label ='Cluster 1')
plt.scatter(X[y_kmeans==2, 0], X[y_kmeans==2,1], s=100, c='Green', label ='Cluster 2')

##################################

plt.scatter(kmeans.cluster_centers_[:,0],
            kmeans.cluster_centers_[:,1], s=300, c='yellow', label ='Centroids')
plt.title('Cluster of Mangoes')
plt.xlabel('Clusters')
plt.ylabel('Cluster Center')
plt.show()
            
